### ISSUE TITLE
 Philips Hue integration failing after 2024.7.4

### ISSUE THREAD

**Issue by tetsuo13** [tetsuo13/home-assistant-config#55]
No issues up to and including the 2024.7.3 release. Log entry:

```
Unknown error connecting to Hue bridge

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 78, in async_initialize_bridge
    await self.api.initialize()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 108, in initialize
    await self.fetch_full_state()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 252, in fetch_full_state
    await asyncio.gather(
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 336, in initialize
    await resource_control.initialize(initial_data)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 80, in initialize
    await self._handle_event(EventType.RESOURCE_ADDED, item)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 209, in _handle_event
    raise exc
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 244, in dataclass_from_dict
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 202, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`GroupedLight.owner` of type `<class 'aiohue.v2.models.resource.ResourceIdentifier'>` is required."
```

Likely related to https://github.com/home-assistant/core/pull/122651

May have to update the firmware on the bridge.

**Comment by tetsuo13** [comment]
No issues with Home Assistant here, it was an outdated firmware on the bridge. Updated it to the latest version, [1965111030](https://www.philips-hue.com/en-us/support/release-notes/bridge), and the integration returned to normal.

The bridge is kept on a network without access to the Internet and only updated every 2-3 years at least. Home Assistant can't be expected to support firmware that old.
